name: RSpec

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install sqlite3
      run: sudo apt-get install libsqlite3-dev
    - name: Install node modules
      run: npm i
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install gems
      run: bundle install --jobs 4 --retry 3
    - name: Run RSpec
      run: bundle exec rspec spec/ --format documentation
